slack_api_url: ENC[AES256_GCM,data:NcUwe5raXknICNijFyScwksgvKj6mNtMRAXCgMdtoZb54kUvgRKthfbV1RYg96HS+xkuohwobk11bi/7QrJJLc7GNq8bNWV5tyyffqkl,iv:vJkoHtVKEqQYNYMk6UaF4Z9gOrc1H74sNGYxlTw2+EQ=,tag:P4RdRJLQv4GwhauMKv/nXw==,type:str]
postgres_exporter_password: ENC[AES256_GCM,data:HFWuBJeyYmRAPmIP+sb48sb/jAUlc9K/AfiAajxXQQ2r+lKkIjXtFw==,iv:PuKtr1XBxWADal5ks8XSnIZ7q5QKuXgCeSp9ioLF9uA=,tag:Y08BRRkcU+I2r94qOz2ziA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:763640948377:alias/dump-monitoring
          created_at: "2026-01-06T22:48:09Z"
          enc: AQICAHhX4LuQwheAofcguwSAs4LXaZRyhKA+5yDW4Ql6UN5YBQFJdvHKkzhlphjqezUb6gmvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHZjytUJOO+BXSWFOAgEQgDvr/mqCxaQOb9hM4Nl54iN9TVVQx9WKvH3O5Rly4QgzIx56Hieqh7tDzoSKtY9PFXZnoConwObQ51DWlg==
          aws_profile: dump-monitoring
    lastmodified: "2026-07-04T17:50:39Z"
    mac: ENC[AES256_GCM,data:O4eKlW4Pt8a+g/wgF6+XBPb4kzBTibzp42Fhibj3wBpxcd4Gkp9hibzBvJUOLBd+Ku0fxVoheHcb7E88B5I5jHoAgLOa+ERv3B7cLBQcDhCD3Dx1UuMUl5p7YEsyoPaIppbL+TMORpuzaeu9feCyuz7ePD6IdjGkxnCMYPjUFJ0=,iv:E62kNh2PfBSX86XD7Fiu9XV7iNtNZpjRWPE0UIVPBH0=,tag:JSX5yWbs7PWL97XYqH1OLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
