---
plugin: aws_ec2
profile: dump-monitoring

regions:
  - eu-central-1

hostnames:
  - ip-address

filters:
  tag:Project: dump-monitoring
  tag:Environment: production

keyed_groups:
  - key: tags.Role
leading_separator: false
