name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  ansible_playbook:
    name: Run Ansible playbook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "./ansible/requirements.txt"

      - name: Install Ansible
        run: |
          pip install -r ./ansible/requirements.txt

      - name: Install Ansible dependencies
        run: |
          ansible-galaxy install -r ./ansible/requirements.yml

      - name: Setup sops
        uses: mdgreenwald/mozilla-sops-action@v1.4.1

      - name: Login to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile dump-monitoring
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile dump-monitoring

      - name: Run Ansible playbook
        run: |
          eval $(ssh-agent)
          ./scripts/ansible-playbook.sh ${{ github.ref_name == 'main' && 'production' || github.ref_name }} monitoring
